### ISSUE TITLE
Low FPS when near turret base

### ISSUE THREAD

**Issue by yocool13** [OpenModularTurretsTeam/OpenModularTurrets#155] opened 2015-08-02 11:16 UTC
I get very low FPS when i come near to a turret base. My FPS is fine when i get out of the area that has one or multiple turret base(s) in it.

**Comment by Poenjabiesous** [comment] 2015-08-02 11:18
We need much more information to be able to help you. 

1. PC spec and allocated ram?
2. Version?
3. Turret type causing issue?
4. Errors in log?

**Comment by yocool13** [comment] 2015-08-02 17:55
PC specs:
Windows 8.1
Processor: AMD E2-6110 APU with AMD Radeon R2 Graphics 1.50 GHz
RAM: 4 GB (This is about 10 GB because external RAM increases)
RAM allocated into Minecraft: 3GB
64 bit OS.
OpenModularTurrets Version:
OpenModularTurrets-1.7.10-2.1.3-163 (JAR file name)
The turrets themselves dont cause the issue but the turret base. All the turret bases cause a decrease in frames.
There were no errors in my server's log nor in my client log.
I am using this mod on my own server. This server has the same version of the mod installed.
My friend also noticed a decrease in frames when near any tier turret base.

**Comment by Keridos** [comment] 2015-08-03 02:58
"RAM: 4 GB (This is about 10 GB because external RAM increases)" and you give Minecraft 3GB, try giving MC 2 gigs.

**Comment by yocool13** [comment] 2015-08-03 11:36
I have noticed better overall performance with only 2 GB in Minecraft, but i still get FPS lag when near a turret base. Isn't more RAM allocated into MC better?

**Comment by Keridos** [comment] 2015-08-03 11:43
More RAM is only better if you crash.

**Comment by Poenjabiesous** [comment] 2015-08-04 16:41
So I tried to reproduce this on a very, very underpowered machine- 1.2GHz dual core with only 2 GB of ram ( 1 of which I gave to the Java VM) and installed FTB Horizons 2 on it. Placed down a magnitude of turret bases and had no difference in FPS or TPS (was basically stuck @ 13 FPS the whole time)

**Comment by yocool13** [comment] 2015-08-04 17:16
Maybe another mod i have installed is messing with ModularTurrets?

**Comment by LazerusKI** [comment] 2015-08-11 17:20
We have noticed the same issue on our server with multiple different client specs (not underpowered)

**Comment by yocool13** [comment] 2015-08-11 17:55
So its a server side thing?

**Comment by LazerusKI** [comment] 2015-08-12 04:24
No, i just wanted to say with that, that it is not only happening for users with a "bad pc", its a general issue that happens even with a high-end machine

**Comment by yocool13** [comment] 2015-08-12 10:22
So can it be fixed?

**Comment by Poenjabiesous** [comment] 2015-08-12 10:26
This is a tough one, as it can't be reproduced reliably- theres no backend code that I can see that can produce an issue like this. It may have something to do with the rendering, but Ill need time to debug.

**Comment by yocool13** [comment] 2015-08-12 10:27
Ok

**Comment by Poenjabiesous** [comment] 2015-08-12 10:33
Does this happen with every turret base that gets placed, or only a percentage of them?

**Comment by LazerusKI** [comment] 2015-08-12 11:22
We have noticed it with the Tier 1, had two blockshooter on it.
also it was not just on visual contact, it was even through walls (they were on the roof)

could there be some kind of calculation or check that happens too often and causes that issue?

**Comment by yocool13** [comment] 2015-08-12 11:39
For me it happenes with every turret base.

**Comment by shazzi2k** [comment] 2015-08-15 17:00
I am getting this on my server. Single player i seem to have no FPS issues what so ever with turrets however on my server i place 4 in certain locations around my base and i am crippled to 7-12fps. I assigned the server 4GB of time to see if this would make a difference however it did not. I will try and make a video.

**Comment by Poenjabiesous** [comment] 2015-08-18 06:59
I have a dumb question.

Do all of you guys here having this issue have AMD CPU's?

**Comment by shazzi2k** [comment] 2015-08-18 07:00
Both my machine and server are using AMD cpus

**Comment by Poenjabiesous** [comment] 2015-08-18 07:04
This might be a chipset architectural/vm threading thing then.

**Comment by yocool13** [comment] 2015-08-18 09:05
Yeah i have an AMD CPU too

**Comment by Poenjabiesous** [comment] 2015-08-18 09:06
I'm beginning to sense a pattern :). I'll look into this.

**Comment by LazerusKI** [comment] 2015-08-18 11:36
Nope, all three on my server have Intel CPUs ;)

**Comment by mskurnik** [comment] 2015-09-03 03:14
We are experiencing a similar bug on my server.  It is happening with both Intel and AMD processors as well as AMD and Nvidia GPUs.  I don't think it could be a server side issue as the server isn't getting any can't keep ups or weird spikes in opis.  What happens on my server is chunks fail to render.  You can walk over the chunks and you don't fall through.  To get the chunk to render you have to just right click with any block in your hand.  There is also a noticeable FPS drop...in some cases down to 1FPS on beefy 16-core machines.

My guess is there is some sort of issue with all of the tile entities.  I hope this post helps.

**Comment by Poenjabiesous** [comment] 2015-09-05 06:38
Can someone please try this build:

https://www.ironhide.de/jenkins/job/OpenModularTurrets/lastSuccessfulBuild/artifact/build/libs/OpenModularTurrets-1.7.10-2.2.0-180.jar

and tell me if the problem is resolved, since I cant replicate it.

**Comment by mskurnik** [comment] 2015-09-05 06:51
@Poenjabiesous I should be able tomorrow when I update the mods on my server.  I will update yours first and see if it improves performance or not.

Thanks!

**Comment by Poenjabiesous** [comment] 2015-09-05 06:58
This is specifically to check the FPS issue.

**Comment by mskurnik** [comment] 2015-09-05 06:59
I've only replicated/tried it on my server.  To try it on my server I would have to update client and server wouldn't I?

**Comment by LazerusKI** [comment] 2015-09-05 09:00
Still broken
http://i1331.photobucket.com/albums/w585/LazerusKI/Minecraft/0_zps2tz6cfc1.png
http://i1331.photobucket.com/albums/w585/LazerusKI/Minecraft/1_zpsykbgojgq.png

**Comment by Poenjabiesous** [comment] 2015-09-05 09:04
Your fps meter is still 60 in those pictures?

**Comment by LazerusKI** [comment] 2015-09-05 09:11
Before Placing it: fps 60, chunk updates 0
after placing it: fps 31, chunk updates 40

**Comment by Keridos** [comment] 2015-09-05 09:27
Hm ok, I did a few patches that should result in less chunk updates. Maybe we need to check for markBlockForUpdate calls.

**Comment by Poenjabiesous** [comment] 2015-09-05 09:45
I think I got it. 5 Secs.

**Comment by Poenjabiesous** [comment] 2015-09-05 09:48
Alright @LazerusKI, try this one:

https://www.ironhide.de/jenkins/job/OpenModularTurrets/181/artifact/build/libs/OpenModularTurrets-1.7.10-2.2.0-181.jar

**Comment by Poenjabiesous** [comment] 2015-09-05 10:07
Yes, it's fixed now. No more chunk update spikes.

**Closed by Poenjabiesous** 2015-09-05 10:07 UTC
Labels: performance

**Comment by Unrepentant-Atheist** [comment] 2015-09-08 09:55
Holy, shit. That FPS shoot up from 14 fps to 30 fps. So THAT what it was...O.o
