### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Sermax18** [OpenModularTurretsTeam/OpenModularTurrets#223] opened 2016-05-08 08:32 UTC
if i place turret base any tier game crashing mods:openmodularturrets opencompunters

**Comment by Keridos** [comment] 2016-05-09 20:26
Wow this issue has almost no info: You are missing the crashlog, the mod version, the forge version, if its SMP or SSP related and finally this is a duplicate of #221.

**Closed by Keridos** 2016-05-09 20:26 UTC
Labels: bug, duplicate
