### ISSUE TITLE
Turret base GUI wont open when holding anything

### ISSUE THREAD

**Issue by Forecaster** [OpenModularTurretsTeam/OpenModularTurrets#149] opened 2015-07-27 17:24 UTC
It's kind of annoying that the base GUI doesn't open when you activate it while holding anything, even if the item is irrelevant to the block, like a sword. And holding relevant items like a turret or ammo doesn't do anything special anyway.

You could make it so clicking with irrelevant items just opens the GUI, clicking with a turret places it on the base, and clicking with ammo will insert it into the inventory.

**Comment by Keridos** [comment] 2015-07-27 17:35
Duplicate of #137

**Closed by Keridos** 2015-07-27 17:35 UTC
