### ISSUE TITLE
Discussion: Compatability for advanced mobs from other mods

### ISSUE THREAD

**Issue by Utildayael** [OpenModularTurretsTeam/OpenModularTurrets#151] opened 2015-07-28 23:09 UTC
This is a bit of a mix of a bug and a feature request because I believe the turrets function 100% wonderfully... against vanilla mobs.

I'm not sure what changes with Lycanites Mobs or Orespawn mobs but the turrets completely ignore them! If a vanilla mob spawns it'll lock on them immediately.

So... requesting future support if possible and not too much hassle! :)

<3

**Comment by grondag** [comment] 2015-08-17 23:57
This likely happening because the getTarget methods in TurretHeadUtil are looking for entities that inherit from EntityLivingBase but Lyacanites (and probably other mobs) do not inherit from that class.

You can see a similar problem (and Lycanite's response that confirms his mobs aren't living entities) here: https://github.com/Lycanite/LycanitesMobs/issues/103

I was able to confirm this bug just now in a test world - turret goes after a Natura Heatscar spider but completely ignore any Lycananites mob I spawn in.

Would *really* love to see this fixed.  I'm using OMT in a hardcore pack that features Lycanites mobs prominently (they make excellent adversaries) but kinda pointless if OMT won't attack them.

**Comment by Utildayael** [comment] 2015-08-18 00:25
Weird. I wonder why he opted to spawn his mobs different than.. well.. most other mods. Annoying.

I'm in the same boat as you. It would be super helpful to have as I'm playing a similar pack. :)

**Comment by Keridos** [comment] 2015-08-18 01:07
The fix for this might make the turrets attack ALL of lycanites mobs, no matter if they are friendly or bad and we would apparently need to implement a compatability fix just for his mod. Why can't he make his bad mobs implement the IMob interface?

**Comment by Utildayael** [comment] 2015-08-18 01:36
Makes sense if he bases all his mobs off same template. I full agree with you Keridos! Might have a reason for doing it the way he did but eh who knows? :)

**Comment by andrenoel1** [comment] 2015-09-28 18:29
I have noticed the same thing when using Open Modular Turets with the mod "Ancient Warefare".  I do believe that the Ancient Warefare coders used a non-standard Entity type that the turrets do not recognize as any target.  

I suspect it will take coding exceptions for each mod in question.  Ideally and unlikely is that the other mod authors develop a standard way of marking their attackable entities.  Perhaps the large well established mods could be written into the Turrets mod as exceptions.  Perhaps these exceptions could be triggered only when the mod in question is installed. 

```
     /** Returns true if the mod id is in the list of loaded mods.
      * @param modId
      * @return
      */
     public static boolean isModIDLoaded(String modId) {
       List<ModContainer> theMods = Loader.instance().getModList();
       Iterator<ModContainer> it = theMods.iterator(); 
       while (it.hasNext()) {
         if ( it.next().getModId().equals(modId) ) { return true; }
       }
       return false;
     }
 ```

Just some related thoughts.
-Andre

**Comment by Keridos** [comment] 2015-09-29 01:09
My problem currently with this is that at this moment we automatically download ALL dependencies needed for the mod via the build.gradle and the versions specified in project.properties. This is really convenient as you can just download the source, do a gradlew build and it should build the mod without any problems. Also gradlew idea and gradlew eclipse do set up a fully working project up.

Since we would most likely need all the mods in a dev version for this fixes to compile and I assume that these mods are not all available via some maven, we might run into issues there.

**Comment by Keridos** [comment] 2015-11-21 12:39
Update: I see not reason why the other mods should not implement IMob for their aggressive mobs.

This issue will not be focused on fixing the not shooting bug, that is up to the other mods authors. This will be unconfirmed and a discussion wether we should do advanced integration for those mods.

**Comment by andrenoel1** [comment] 2015-11-22 03:21
Ok, thanks.  =)

Keridos wrote:

**Comment by Keridos** [comment] 2015-11-22 15:11
By the way, the targetting (at least for lycanitesmobs) should be fixed in this build: https://www.ironhide.de/jenkins/job/OpenModularTurrets/190/. Can some of you maybe test that?

**Comment by Poenjabiesous** [comment] 2015-12-25 22:44
We can keep this ticket open, but I'm marking it as invalid as I agree with @Keridos-  There is no reason for mod authors not to use the standard IMob interface for their implementations. We can't do integration work for every mod out there that adds mobs to the game.

**Comment by shadoxxhd** [comment] 2016-01-26 21:36
you could add a setting to allow a "target every entity" mode, or let the modpack creator (or anyone with access to the configs) add entity names/ids to the target list.

**Comment by Utildayael** [comment] 2016-01-28 17:52
Not a bad idea. Not sure how hard it is from a code perspective but would keep the team from ever having to do "custom" integration work.

**Comment by Poenjabiesous** [comment] 2016-01-28 18:01
Two issues here: 

1. One can not try to target everything that extends from the class "Entity", as an entity is anything from dropped items to projectiles (I even think that FX sprites are seen as entities by the engine).

2. Making a string iterable "list" of additional entities that should be targeted will be extremely difficult to administer, as a entity's in-game name is not its backend name. For instance, a Creeper might be called "entityCreeper", or "mobCreeper", as an actual referenced localized name- which will almost never be easy to attain from source code/devs/etc.

**Comment by shadoxxhd** [comment] 2016-01-28 18:59
1. targeting items and fireballs could be intended by the user. if not, it'd be always possible to add items/projectiles/... to the blacklist (or remove it from the whitelist)

2. can you get the class name string from within the code?

**Closed** 2016-12-05 19:57 UTC
Labels: feature request, invalid
