### ISSUE TITLE
[SUGGESTION]  Fences (ALL tiers)

### ISSUE THREAD

**Issue by gp009** [OpenModularTurretsTeam/OpenModularTurrets#207] opened 2016-02-28 07:28 UTC
fences are good except they should be owner friendly ( not damaging the player who places them ).

it gets quite frustrating to put these fences up without getting killed

**Comment by Poenjabiesous** [comment] 2016-03-04 06:52
I tried this with the initial implementation of the fences- the problem is that the fences are blocks without a tile entity (Like it should be in my opinion). So, storing data about who placed the fence is not possible, since blocks only have a metadata integer that must be <16 to store state in.

I will have a look at Thaumcraft's warded glass (as I suppose they are only blocks as well, but I may be wrong) to see how this problem was solved.

**Comment by Poenjabiesous** [comment] 2016-03-14 12:30
This is not possible without TE's at this point in time. I'm closing the ticket but will keep an eye out for a solution, if one exists.

**Closed by Poenjabiesous** 2016-03-14 12:30 UTC
