### ISSUE TITLE
OpenComputers-OpenModularTurrets-IC2 api conflict

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [OpenModularTurretsTeam/OpenModularTurrets#221] opened 2016-05-07 12:19 UTC
Hello,

I upgraded open modular turrets and I don't play IC2:

java.lang.NoClassDefFoundError: ic2/api/energy/tile/IEnergyTile

this happen as soon as I place a turrets base in the world and I can't open/join the map anymore.

Thank you for your time.

PS: i already disabled ic2 support in the config but it crash still.

**Comment by Keridos** [comment] 2016-05-07 12:22
This is already been reported and is being caused by another mod, I will probably add a second check to see it the config is disabled. Short story: Will be fixed but you have to disable the config manually.

For some reason some other mods makes forge believe IC2 is installed although it isn't. Can you please provide a crash report?

**Comment by Ganjalf-Amsterdoom** [comment] 2016-05-07 12:25
Yes, of course, and thank you so much for the quick answer:

http://pastebin.com/dQMLqtTM

**Comment by Keridos** [comment] 2016-05-07 13:37
If you want to help us fix this bug and have some spare time, can you try to determine which mod causes that?
You could do that with removing mod by mod until the server does not crash anymore.

**Comment by Ganjalf-Amsterdoom** [comment] 2016-05-07 14:38
I will try that, and get back to you asap. Thank you.

**Comment by Ganjalf-Amsterdoom** [comment] 2016-05-07 19:57
I've spent about 4 hours "cherry picking" mods from my modpack, when I remove OpenComputers then openmodularturrets works without giving the missing IC2 error.

Could you aproach openCC devs to see if they can do anything?

Thank you for your time.

**Comment by fnuecke** [comment] 2016-05-08 18:18
Looks like the `@Optional` is failing to strip the interface. (And no, OC isn't shipping a partial IC2 API). 

I've had this issue myself with other mods before, and know of some other modders who have also run into that issue. I never figured out the actual cause - nor did anyone I've talked to about this. I ended up using a custom transformer for my internal classes that *adds* the interfaces instead of stripping them, which appears to work more reliably... for whatever reason.

Soooo... unless someone knows what causes `@Optional` to fail and how to work around it, I'm afraid there's nothing I can do about this :/

**Comment by Keridos** [comment] 2016-05-09 00:14
@fnuecke Maybe take a look at this issue, might be the same bug in FML. The commit fixing that issue is what we had to do. In our case initializing our gui handler on declaration caused Railcraft to believe that Thaumcraft was installed. No idea what weird thing in FML causes that though.

**Comment by fnuecke** [comment] 2016-05-09 07:28
That sounds related, aye. OC doesn't have a GUIHandler, though; I'll see if I can reproduce and then work around it by messing with the initialization logic when I find the time (Wednesday at the soonest I'm afraid).

**Comment by Ganjalf-Amsterdoom** [comment] 2016-05-09 10:47
Just to mention it, I never implied OC is shipping ic2 api. :D 

Thank you so much guys for looking into the issue.

**Comment by LemADEC** [comment] 2016-05-09 20:06
I use @Optional quite a bit in my mod and the only issues I have is when:
1- another mod comes with a partial API.
2- a coremod tries to load a class while all other transformers didn't go through yet.

**Comment by RedGuy54** [comment] 2016-05-09 23:41
I'm having this same issue, so right now there's nothing right now to fix it?

**Comment by Keridos** [comment] 2016-05-10 00:09
We can not automatically fix this easily, we can release a patch that makes it go away when you deactivate it manually in the config.

**Comment by RedGuy54** [comment] 2016-05-10 00:46
Ok, right now I just installed IC2 in my modpack to fix the problem.

**Comment by Ganjalf-Amsterdoom** [comment] 2016-05-10 07:52
same here as redguy54, but guys thank you for taking your time to bring the issue to the surface.

**Comment by Keridos** [comment] 2016-06-03 02:38
@fnuecke Some progress on this?

**Comment by fnuecke** [comment] 2016-06-04 12:15
Looking into it now.

FYI: was hoping to test in dev, but looks like your Jenkins has the same issue I once had, with it shoving all files into the JAR twice (just take a peek into the -dev JAR). Pretty sure the problem is [those lines in your `build.gradle`](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/master/build.gradle#L123-L128). [This is how I fixed it for OC](https://github.com/MightyPirates/OpenComputers/commit/603f23a0fb3e77644625713f22df657cc0b67030#diff-c197962302397baf3a4cc36463dce5eaR289), going by the history.

**Comment by fnuecke** [comment] 2016-06-04 14:07
Welp, tried removing the initialization stuff from the `OpenComputers` class, no luck. Then I thought it might be the FML transformer taking care of the `@Optional`s not running for some reason because OC's runs on the class. So I applied the "strip all the things that don't exist" logic I have for my stuff anyway to `SimpleComponent`s (and thus `TurretBase`). No luck. I have no idea how in the world this interface is still referenced after having quite clearly been stripped from the class... any more ideas very much welcome.

**Comment by Keridos** [comment] 2016-06-08 06:47
This seems to be weird, I am not sure If I am able to follow you completely there, never did anything much beyond simple breakpoint debugging in java yet.

**Comment by fnuecke** [comment] 2016-06-08 14:44
Trying to reword this: the issue only occurs if OC's class transformer injects the things needed to make `SimpleComponent` work. So I suspected that might throw off FML's transformer that takes care of `@Optional` (stripping interfaces of missing mods). So I just did that in OC's transformer, too, but it still errored due to the missing interface (even though it was definitely gone from the class definition).

Side note: I had that issue with OC's classes, too, which is why I switched to *injecting* the interfaces if the mods were present, instead of *stripping* them. Not really an option here, though.

De-duplication: awesome, that should make more experimenting a lot faster!

**Comment by Ganjalf-Amsterdoom** [comment] 2016-07-08 07:07
Any news on this issue? Is there a build of open modular turrets or opencomputers that will allow to play this two mods together without installing IC2?
Thank you guys for your time @fnuecke @Keridos

**Comment by cpm9** [comment] 2016-07-09 03:31
I'm having the same issue.

**Comment by Keridos** [comment] 2016-07-13 00:33
I think the latest build may fix that, worked in local testing. It is really ugly though and a proper fix would be welcome. @fnuecke Any more progress on this?

**Comment by VoltyFarstar** [comment] 2016-07-13 07:19
@Keridos I can confirm that I'm also not receiving the error in the latest build.

**Comment by fnuecke** [comment] 2016-07-13 17:40
Sorry, was busy and then on vacation. I don't really have any more ideas, but I will have another stab at it when I can.

**Comment by Ganjalf-Amsterdoom** [comment] 2016-07-29 08:50
Just to comment on it, I installed latest release from curseforge of OMT with OC and without IC2 and loaded game and worlds without any issue, I'm assuming everything works fine, didn't do any test like placing turrets or anything.

**Closed** 2016-08-05 10:40 UTC
Labels: confirmed, duplicate, external
