### ISSUE TITLE
Cant break turret base

### ISSUE THREAD

**Issue by aidancrazywierd** [OpenModularTurretsTeam/OpenModularTurrets#162] opened 2015-08-16 22:12 UTC
In servers the button you click to break turret base/ turret/ trust players isnt there, but in singleplayer it is.

**Comment by Keridos** [comment] 2015-08-17 02:52
Duplicate of #161 and #123. Server is probably in offline mode, set it to online mode and you are fine. Can also be caused by some weird launcher bug or when the mojang servers are down.

**Comment by aidancrazywierd** [comment] 2015-08-18 02:28
yes it is because of the server being in offline mode, the owner of OhGaming would like to discuss that with you, if he hasnt already.

**Comment by Keridos** [comment] 2015-08-18 02:30
The thing is that we would need to make the entire UUID system compatible with offline mode. Second thing is that I think 99,9% of the people who use offline mode make it to make cracked clients possible to join their server and me and @Poenjabiesous have agreed that we will NOT make this mod compatible with cracked clients.

**Comment by aidancrazywierd** [comment] 2015-08-18 03:01
hm ok, i will inform

**Comment by Poenjabiesous** [comment] 2015-08-18 05:08
I completely agree with Keridos, we cant endorse, support or help cracked players and/or servers.

**Comment by aidancrazywierd** [comment] 2015-08-18 05:14
I didnt know about the offline server being open to cracked players because im just a player myself who bought the game and plays ont he server trying to help get the mod working :)

**Comment by oaksvirals** [comment] 2015-08-18 05:21
Hello, It's for bungeecord. That's why the server is in Offline mode. Is there no work around available?

**Comment by Poenjabiesous** [comment] 2015-08-18 06:56
Hi Oaksvirals

Unfortunately not. Allow me to explain:

From MC 1.7.10, premium players could start changing their player names. This posed a big problem for the modding community in terms of block ownership; we would usually check if a player is the owner or not (during certain operations) by checking it's displayName with a stored displayName. Since players could start changing those, we started using player UUID's (from Mojang) so that players could change their names but still retain ownership.

When a server is in offline mode, that call to Mojang that retrieves a specific players' UUID does not happen. So, there is no way for the turret base to then know who the owner is, since the UUID of the owner is empty/null.

**Comment by oaksvirals** [comment] 2015-08-18 08:37
Thanks for the response Poenjabiesous,

Yea, it's unfortunate for us. We'll have to make due with it though.

Thanks again.

**Comment by Keridos** [comment] 2015-08-18 17:35
The thing is that fixing that would NOT be a simple fix at all and might break compatability of savegames. In addition to the whole "cracked" clients thing.

**Comment by Poenjabiesous** [comment] 2015-09-05 05:23
Closing this.

**Closed by Poenjabiesous** 2015-09-05 05:23 UTC
Labels: invalid
