### ISSUE TITLE
owner bug

### ISSUE THREAD

**Issue by Rofle44** [OpenModularTurretsTeam/OpenModularTurrets#486] opened 2019-07-03 23:22 UTC
#### Issue Description:

when i close the game and re enter it the turret doesnt belong to me anymore.
im playing in my own world alone if that helps. this happens with a lot of other mods like scurity craft and blockling mod pls help

#### What you expected to happen:
the GUI is supposed to popup

#### Steps to reproduce:

1. i dont
2. know what 
3. that means
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT: ;3.1.3
- OMLib: ;3.1.3
- Minecraft: ;1.12.2
- Forge: ;1.12.2
- SpongeForge? yes/no ;no
- Optifine? yes/no ;no
- Single Player and/or Server? ;single player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by Keridos** [comment] 2019-07-04 09:00
duplicate of #378 #278 and #135. Please see our FAQ for more info.

**Closed as completed by Keridos** 2019-07-04 09:00 UTC
Labels: invalid
