### ISSUE TITLE
[1.11.2] Crash with OC integration

### ISSUE THREAD

**Issue by BrisingrAerowing** [OpenModularTurretsTeam/OpenModularTurrets#356] opened 2017-07-12 14:50 UTC
[Crash Log](https://gist.github.com/BrisingrAerowing/b555943d73420ce1b12e1476fad0f77c)

OMT: 3.0.0-182
OMLib: 3.0.0-110
Forge: 13.20.1.2393
OC: 1.7.0-git (custom build for some unreleased features / fixes)

**Comment by Keridos** [comment] 2017-07-12 14:51
Ah yeah, probably know why this crashes...

**Comment by Keridos** [comment] 2017-07-12 15:01
Nevermind, there is something wrong there, not sure if its caused by our mod.

**Comment by sandalle** [comment] 2017-07-12 17:09
Same issue after updating to Open Modular Turrets 1.10.2-3.0.0-182 from 1.10.2-3.0.0-158 and OMLib 1.11.2-3.0.0-110 from 1.11.2-3.0.0-100 on Minecraft 1.11.2 with Forge Mod Loader 1.11.2-13.20.1.2393.

Downgrading to Open Modular Turrets 1.10.2-3.0.0-158 fixes the issue, leaving OMLib at  1.11.2-3.0.0-110 let's my world load.

crash-report: [crash-2017-07-12_09.58.21-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1142770/crash-2017-07-12_09.58.21-server.txt)

**Comment by Keridos** [comment] 2017-07-12 21:26
Yeah I know why this is happening, but this bug is not in OMT or OMlib... its either forge or OC bugging annotations.

**Comment by Keridos** [comment] 2017-07-13 02:46
Fixed in newest releases on curseforge (may still need to be approved). Thanks for reporting

**Closed by Keridos** 2017-07-13 02:46 UTC
Labels: bug, confirmed, external

**Comment by sandalle** [comment] 2017-07-13 05:40
Works for me, thank you for the quick fix! :)
