### ISSUE TITLE
Turrets cannot hit baby skeletons from Mekanism

### ISSUE THREAD

**Issue by dat3ngy** [OpenModularTurretsTeam/OpenModularTurrets#298] opened 2017-03-28 02:50 UTC
The turrets seem to aim too high when attacking baby skeletons. This doesn't happen with baby zombies however. Tested this in Minecraft 1.10.2 with Forge 1.10.2 - 12.18.3.2254, using Open Modular Turrets 1.10.2-3.0.0-100 and OMLib 1.10.2-3.0.0-61 along with Mekanism 1.10.2-9.2.2.301 and a couple other mods.  This bug might affect other versions as well. If you'd like me to provide more information such as logs and screenshots, I'd be happy to comply. Thanks in advance.

**Comment by Keridos** [comment] 2017-03-28 09:51
As far as i know we are aiming at the mobs "eyes" currently. Gonna take a look at this as well. Might affect other mobs, too.

On 28 March 2017 04:50:26 GMT+02:00, dat3ngy <notifications@github.com> wrote:
>The turrets seem to aim too high when attacking baby skeletons. This
>doesn't happen with baby zombies however. Tested this in Minecraft
>1.10.2 with Forge 1.10.2 - 12.18.3.2254, using Open Modular Turrets
>1.10.2-3.0.0-100 and OMLib 1.10.2-3.0.0-61 along with Mekanism
>1.10.2-9.2.2.301 and a couple other mods.  This bug might affect other
>versions as well. If you'd like me to provide more information such as
>logs and screenshots, I'd be happy to comply. Thanks in advance.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/298

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Keridos** [comment] 2017-05-08 12:46
Duplicate of #259

**Closed by Keridos** 2017-05-08 12:46 UTC
Labels: bug, confirmed, duplicate
