### ISSUE TITLE
Opening GUI for targetting mobs/neutrals/players results in hard client crash

### ISSUE THREAD

**Issue by plazia** [OpenModularTurretsTeam/OpenModularTurrets#164] opened 2015-08-26 22:30 UTC
Version 2.1.3-163

Opening my tier 5 turret base with an empty hand gives me the normal GUI however when I click config to change the targetting like mobs/neutrals/players the GUI loads but results in a hard client crash to desktop.

Crash report here: http://pastebin.com/eSs2eqEM

Another issue I'm experiencing is horrible FPS problems with just 4 open modular turrets around my base supplied by ender io energy conduits. I would get periodic stuttering in rendering framerate. Incredibly noticeable.

Since removing the 4 turrets from around my base -  FPS has settled back to a nice stable 100 FPS (ish) around my base area. I would be lucky to get 70 with Open Modular Turrets and it was intermittantly stuttery at that.

I hope this issue can be resolved as I feel it's an absolutely AWESOME mod.

My specs (if this helps to diagnose)
i5 3570k @ 4.4 GHz
16 GiB RAM
GTX 660 Ti
SSD
blah blah. Win 7 Java 8

**Comment by Keridos** [comment] 2015-08-27 04:44
This is weird, looks as if the inventory disappears when going into the other GUI. We never had that issue before.

As for the FPS drop, we still have no idea why that is happening and we were not able to reproduce it yet.

**Comment by Poenjabiesous** [comment] 2015-09-05 05:28
Did this happen more than once?

**Comment by Poenjabiesous** [comment] 2015-09-05 05:59
I am unable to replicate this.

**Comment by Keridos** [comment] 2015-09-08 15:32
The fps drop should be fixed in  b489027ddc4fde0517e65988d5f98019c1d40779.
For the crash I am unable to replicate the crash in Single and Multiplayer. Closing the issue now.

**Closed by Keridos** 2015-09-08 15:32 UTC
Labels: bug, needs testing
