### ISSUE TITLE
Inconsistency with RF Generation from Redstone

### ISSUE THREAD

**Issue by nanakisan** [OpenModularTurretsTeam/OpenModularTurrets#145] opened 2015-07-25 05:54 UTC
As per to the tool-tip for the Redstone Reactor addon. 1550 RF "per" "dust" consumed. If calculation is valid using this information. a stack of RS should yield 99,200RF. Which is not the case. The actual generation is 100RF per dust. Also the reactor does not account for blocks of RS. It will consume the blocks but only count it as 1 piece of redstone and not 9.

**Comment by Keridos** [comment] 2015-07-25 06:00
Which version of OMT are you using?

**Comment by nanakisan** [comment] 2015-07-25 06:22
v2.1.0-151 I grabbed it yesterday and started testing.

**Comment by Keridos** [comment] 2015-07-25 06:23
AS I said, for me it works flawlessly even without the newest patches, but try out this:  https://www.ironhide.de/jenkins/job/OpenModularTurrets/lastSuccessfulBuild/artifact/build/libs/OpenModularTurrets-1.7.10-2.1.1-157.jar

**Comment by nanakisan** [comment] 2015-07-25 06:24
Testing now

**Comment by nanakisan** [comment] 2015-07-25 06:30
Version provided,  
Redstone Reactor is now non-functional and will not convert RS into RF.  
https://imgur.com/a/2Cl2T

**Comment by Keridos** [comment] 2015-07-25 06:33
I still cannot reproduce that in my dev environment. For me it works fine in SSP and it should also work fine in SMP

**Comment by nanakisan** [comment] 2015-07-25 06:38
very weird then. I am presently using forge 1448. Would that explain anything?  
  
Otherwise here is a rundown of all mods using the RF API in my pack  
Mekanism v8 v8.1.5 
Immersive Engineering  
Railcraft  Latest version
Modular Armor  Latest version
Engineers Toolbox Most recent stable release
Buildcraft 7.016

**Comment by Keridos** [comment] 2015-07-25 06:38
Ok this is strange, it works in my dev environment but not in my other instances, gonna need some more testing there.

**Comment by Poenjabiesous** [comment] 2015-07-25 07:30
Also working in my dev env. Strange.

**Comment by Keridos** [comment] 2015-07-25 22:30
Test this here please, I am pretty certain it is fixed now: https://www.ironhide.de/jenkins/job/OpenModularTurrets/lastSuccessfulBuild/artifact/build/libs/OpenModularTurrets-1.7.10-2.1.1-159.jar

**Closed** 2015-07-25 22:29 UTC
Labels: bug, confirmed

**Comment by nanakisan** [comment] 2015-07-26 00:19
Confirmed as working now with latest version.
