### ISSUE TITLE
Cant Configure Turret Base

### ISSUE THREAD

**Issue by Daaaniel0631** [OpenModularTurretsTeam/OpenModularTurrets#406] opened 2018-03-18 10:19 UTC
I have Forge server and i have some mods on the server, but when I try to configure the turret it does not show me the offer with confugation as in single-player, please help and advice what it might be

**Comment by Keridos** [comment] 2018-03-18 12:39
Duplicate of a lot of issues, search through the closed issues please.

**Closed by Keridos** 2018-03-18 12:39 UTC

**Comment by Keridos** [comment] 2018-03-19 00:05
Duplicate of a lot of issues, search through the closed issues please.
